version: "3.3"

services:
    psql:
        container_name: psql
        image: postgres
        restart: always
        ports:
            - ${APP_DB_PORT:-5432}:5432
        volumes:
            - psqlVolume:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: ${APP_DB_NAME:-hits}
            POSTGRES_USER: ${APP_DB_USER:-admin}
            POSTGRES_PASSWORD: ${APP_DB_PASS:-secret}
        networks:
            - djangoNet

    django:
        container_name: django
        build: .
        volumes:
            - ./docker/django/static:/code/static
            - .:/code
        depends_on:
            - psql
        env_file:
            - .env
        networks:
            - djangoNet

    nginx:
        container_name: nginx
        image: nginx:alpine
        volumes:
            - ./docker/nginx/sites:/etc/nginx/conf.d
            - ./docker/django/static:/code/static
        ports:
            - ${APP_PORT:-80}:80
        depends_on:
            - django
        networks:
            - djangoNet

    redis:
        container_name: redis
        image: redis:6
        restart: always
        networks:
            - djangoNet

networks:
    djangoNet:
        driver: "bridge"

volumes:
    psqlVolume:
